url: https://tirelesswake.github.io/royall
baseurl:

# Site settings
title: Royall Design
email: info@royalldesign.com
description: "Royall Design is a full service design company that specializes in graphic design, web design and social media for your business or organization."


# Team names, titles and social links
people:
- name: Sarah
  pic: 1
  position: Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    # - title: stack-overflow
    #   url: #

- name: Roy
  pic: 2
  position: Graphics
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

# - name: Diana Petersen
#   pic: 3
#   position: Lead Developer
#   social:
#     - title: twitter
#       url: #
#     - title: facebook
#       url: #
#     - title: google-plus
#       url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/royalldesign
  - title: facebook
    url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/sarah979c

# Postal address (add as many lines as necessary)
address:
  - line: 520 Chester Ave
  - line: Ottumwa, IA 52501

# Build settings
markdown: kramdown
permalink: pretty
